[project]
name = "tool-agent-demo"
version = "0.1.0"
description = "Add your description here"
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["click>=8.1.8", "pydantic>=2.10.5"]

[project.scripts]
tool-agent-demo = "tool_agent_demo.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.3.4"]

[tool.pytest.ini_options]
filterwarnings = ["ignore::pytest.PytestCollectionWarning"]
